// ============================================================
// Download Utility — Export trip itinerary as a formatted text file
// ============================================================

import type { Trip } from '@shared/types/index';

/** Generates a beautifully formatted plaintext itinerary */
function formatItinerary(trip: Trip): string {
  const lines: string[] = [];

  lines.push('═'.repeat(60));
  lines.push(`  🌍 ${trip.name}`);
  lines.push('═'.repeat(60));
  lines.push('');
  lines.push(`📍 Destination: ${trip.preferences.destination}`);
  lines.push(`📅 Dates: ${trip.preferences.startDate} → ${trip.preferences.endDate}`);
  lines.push(`💰 Total Budget: ₹${trip.totalCost.toLocaleString('en-IN')}`);
  lines.push(`🎯 Trip Type: ${trip.preferences.tripType}`);
  lines.push(`🏃 Pace: ${trip.preferences.pace}`);
  lines.push(`✨ Style: ${trip.preferences.travelStyle.join(', ')}`);
  if (trip.preferences.origin) {
    lines.push(`🏠 Origin: ${trip.preferences.origin}`);
  }
  lines.push('');

  for (const day of trip.days) {
    lines.push('─'.repeat(60));
    const dateStr = new Date(day.date).toLocaleDateString('en-US', {
      weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
    });
    lines.push(`📅 Day ${day.dayNumber} — ${dateStr}`);
    lines.push(`   🌤️ Weather: ${day.weather.condition} (${day.weather.high}°/${day.weather.low}°, ${day.weather.rainProbability}% rain)`);
    lines.push(`   📊 Feasibility: ${day.feasibilityScore}%`);
    lines.push('');

    for (const activity of day.activities) {
      const costStr = activity.cost > 0 ? ` | ₹${activity.cost.toLocaleString('en-IN')}` : '';
      const outdoorStr = activity.weather.isOutdoor ? ' | 🌤️ Outdoor' : '';
      lines.push(`   ${activity.startTime}  ${getCategoryEmoji(activity.category)} ${activity.name}`);
      lines.push(`            ${activity.description}`);
      lines.push(`            ⏱️ ${activity.duration} min${costStr}${outdoorStr}`);
      lines.push(`            📍 ${activity.location.address}`);

      if (activity.transitFromPrevious) {
        const t = activity.transitFromPrevious;
        const modeEmoji = t.mode === 'walking' ? '🚶' : t.mode === 'transit' ? '🚇' : '🚗';
        lines.push(`            ${modeEmoji} ${t.duration} min · ${t.distance}`);
      }
      lines.push('');
    }
  }

  lines.push('─'.repeat(60));
  lines.push('');
  lines.push(`💰 TOTAL ESTIMATED COST: ₹${trip.totalCost.toLocaleString('en-IN')}`);
  lines.push('');
  lines.push('Generated by RoamGenie — AI-Powered Travel Planner');
  lines.push(`Exported on ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}`);
  lines.push('');

  return lines.join('\n');
}

function getCategoryEmoji(category: string): string {
  const map: Record<string, string> = {
    food: '🍜', culture: '🏛️', nature: '🌿', shopping: '🛍️',
    nightlife: '🌃', transit: '🚶', accommodation: '🏨', entertainment: '🎭',
  };
  return map[category] ?? '📌';
}

/** Triggers browser download of the itinerary as a .txt file */
export function downloadItinerary(trip: Trip): void {
  const content = formatItinerary(trip);
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${trip.name.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_')}_itinerary.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
